// Generated by CoffeeScript 1.6.3
/*
This is Game Of Life
Author Rafael Cosman
*/


(function() {
  var ages, background, c, circle, context, createArray, draw, fillRect, fillStyle, getBinaryThingey, gridHeight, gridWidth, inc, makeNewGrid, println, randomGrid, randomizeGrid, restore, rules, save, translate;

  c = document.getElementById("myCanvas");

  context = c.getContext("2d");

  translate = function(x, y) {
    return context.translate(x, y);
  };

  fillRect = function(width, height) {
    return context.fillRect(0, 0, width, height);
  };

  circle = function(radius) {
    return context.arc(0, 0, radius, 0, 2 * Math.PI, false);
  };

  background = function() {
    var bigNum;
    bigNum = 100000;
    return context.fillRect(-bigNum, -bigNum, 2 * bigNum, 2 * bigNum);
  };

  fillStyle = function(string) {
    return context.fillStyle = string;
  };

  save = function() {
    return context.save();
  };

  restore = function() {
    return context.restore();
  };

  println = function(obj) {
    return console.log(obj);
  };

  createArray = function(length) {
    var args, arr, i;
    arr = new Array(length || 0);
    i = length;
    if (arguments_.length > 1) {
      args = Array.prototype.slice.call(arguments_, 1);
      while (i--) {
        arr[length - 1 - i] = createArray.apply(this, args);
      }
    }
    return arr;
  };

  makeNewGrid = function() {
    var x, y, _i, _results;
    _results = [];
    for (x = _i = 0; 0 <= gridWidth ? _i < gridWidth : _i > gridWidth; x = 0 <= gridWidth ? ++_i : --_i) {
      _results.push((function() {
        var _j, _results1;
        _results1 = [];
        for (y = _j = 0; 0 <= gridHeight ? _j < gridHeight : _j > gridHeight; y = 0 <= gridHeight ? ++_j : --_j) {
          _results1.push(0);
        }
        return _results1;
      })());
    }
    return _results;
  };

  randomizeGrid = function() {
    var ages;
    return ages = randomGrid;
  };

  randomGrid = function() {
    var x, y, _i, _results;
    _results = [];
    for (x = _i = 0; 0 <= gridWidth ? _i < gridWidth : _i > gridWidth; x = 0 <= gridWidth ? ++_i : --_i) {
      _results.push((function() {
        var _j, _results1;
        _results1 = [];
        for (y = _j = 0; 0 <= gridHeight ? _j < gridHeight : _j > gridHeight; y = 0 <= gridHeight ? ++_j : --_j) {
          _results1.push(Math.floor(Math.random() + .5));
        }
        return _results1;
      })());
    }
    return _results;
  };

  getBinaryThingey = function(num) {
    if (num === 0) {
      return 0;
    } else {
      return 1;
    }
  };

  inc = function(arr, x, y) {
    if (x > 0 && y > 0 && x < arr.length && y > arr[0].length) {
      println("WHOOP!");
      return arr[x][y]++;
    }
  };

  draw = function() {
    var numNeighbors, x, y, _i, _j, _k, _l, _m, _n, _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
    numNeighbors = makeNewGrid();
    for (x = _i = 0, _ref = gridWidth - 1; 0 <= _ref ? _i < _ref : _i > _ref; x = 0 <= _ref ? ++_i : --_i) {
      for (y = _j = 0, _ref1 = gridHeight - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; y = 0 <= _ref1 ? ++_j : --_j) {
        if (ages[x][y] !== 0) {
          println("LOL");
          inc(numNeighbors, x - 1, y - 1);
          inc(numNeighbors, x - 1, y);
          inc(numNeighbors, x - 1, y + 1);
          inc(numNeighbors, x, y - 1);
          inc(numNeighbors, x, y + 1);
          inc(numNeighbors, x + 1, y - 1);
          inc(numNeighbors, x + 1, y);
          inc(numNeighbors, x + 1, y + 1);
        }
      }
    }
    println(numNeighbors[0]);
    for (x = _k = 0, _ref2 = gridWidth - 1; 0 <= _ref2 ? _k < _ref2 : _k > _ref2; x = 0 <= _ref2 ? ++_k : --_k) {
      for (y = _l = 0, _ref3 = gridHeight - 1; 0 <= _ref3 ? _l <= _ref3 : _l >= _ref3; y = 0 <= _ref3 ? ++_l : --_l) {
        if (rules[getBinaryThingey(ages[x][y])][numNeighbors[x][y]]) {
          ages[x][y]++;
        } else {
          ages[x][y] = 0;
        }
      }
    }
    background(0);
    println(ages[0]);
    for (x = _m = 0, _ref4 = gridWidth - 1; 0 <= _ref4 ? _m < _ref4 : _m > _ref4; x = 0 <= _ref4 ? ++_m : --_m) {
      for (y = _n = 0, _ref5 = gridHeight - 1; 0 <= _ref5 ? _n <= _ref5 : _n >= _ref5; y = 0 <= _ref5 ? ++_n : --_n) {
        save();
        translate(10 * x, 10 * y);
        if (ages[x][y] !== 0) {
          fillStyle("FF0000");
          fillRect(5, 5);
        }
        restore();
      }
    }
    return setTimeout(draw, 1000);
  };

  gridWidth = 300;

  gridHeight = 300;

  context.shadowBlur = 20;

  ages = makeNewGrid();

  ages = randomGrid();

  println(ages[0]);

  rules = [[false, false, false, true, false, false, false, false, false], [false, false, true, true, false, false, false, false, false]];

  draw();

}).call(this);
