// Generated by CoffeeScript 1.6.3
(function() {
  var hello, port;

  port = Number(process.env.PORT || 3000);

  hello = require('zappajs')(port, function() {
    this.get({
      '/': function() {
        return this.render({
          index: {
            'name': 'world'
          }
        });
      }
    });
    this.view({
      index: function() {
        var canvas, processingInstance;
        this.title = 'Greeetz';
        h1("Demooo site");
        p("Hello " + this.name);
        script({
          src: 'https://github.com/downloads/processing-js/processing-js/processing-1.4.1.js'
        });
        canvas({
          id: 'canvas1'
        });
        canvas = document.getElementById("canvas1");
        return processingInstance = new Processing(canvas, sketchProc);
      }
    });
    this.view({
      layout: function() {
        doctype(5);
        return html(function() {
          head(function() {
            script({
              src: "/logicBox.coffee"
            });
            title(this.title);
            title("TEST");
            return link({
              rel: "stylesheet",
              href: "/base.css"
            });
          });
          return body(this.body);
        });
      }
    });
    return this.css({
      '/base.css': 'body {\n	margin-left: auto;\n	margin-right: auto;\n	width:80%;\n	font-family: sans-serif;\n	margin-top: 2em;\n}'
    });
  });

}).call(this);
