// Generated by CoffeeScript 1.6.3
(function() {
  var c, context, ellipseByDimensions, ellipseByLocationAndDimensions, ellipseByLocationAndRadius, ellipseByRadius, rectByLocationAndDimensions, translateByLocation;

  c = document.getElementById("myCanvas");

  context = c.getContext("2d");

  translate(function(x, y) {
    return context.translate(x, y);
  });

  fillRect(function(width, height) {
    return context.fillRect(0, 0, width, height);
  });

  circle(function(radius) {
    return context.arc(0, 0, radius, 0, 2 * Math.PI, false);
  });

  ellipseByLocationAndDimensions = function(location, dimensions) {
    return ellipse(location.x, location.y, dimensions.x, dimensions.y);
  };

  ellipseByLocationAndRadius = function(location, radius) {
    return ellipse(location.x, location.y, radius * 2, radius * 2);
  };

  ellipseByDimensions = function(dimensions) {
    return ellipse(0, 0, dimensions, dimensions);
  };

  ellipseByRadius = function(radius) {
    return ellipse(0, 0, radius * 2, radius * 2);
  };

  rectByLocationAndDimensions = function(location, dimensions) {
    return rect(location.x, location.y, dimensions.x, dimensions.y);
  };

  translateByLocation = function(location) {
    return translate(location.x, location.y);
  };

}).call(this);
