// Generated by CoffeeScript 1.6.3
(function() {
  var ellipseByDimensions, ellipseByLocationAndDimensions, ellipseByLocationAndRadius, ellipseByRadius, rectByLocationAndDimensions, translateByLocation;

  ellipseByLocationAndDimensions = function(location, dimensions) {
    return ellipse(location.x, location.y, dimensions.x, dimensions.y);
  };

  ellipseByLocationAndRadius = function(location, radius) {
    return ellipse(location.x, location.y, radius * 2, radius * 2);
  };

  ellipseByDimensions = function(dimensions) {
    return ellipse(0, 0, dimensions, dimensions);
  };

  ellipseByRadius = function(radius) {
    return ellipse(0, 0, radius * 2, radius * 2);
  };

  rectByLocationAndDimensions = function(location, dimensions) {
    return rect(location.x, location.y, dimensions.x, dimensions.y);
  };

  translateByLocation = function(location) {
    return translate(location.x, location.y);
  };

}).call(this);
